name: Build Docker images


on:

  push:
    branches: 
      - "8.4"
      - "8.3"
      - "8.2"
      - "8.1"
      - "7.4"

  schedule:
    - cron: "0 0 * * 4"

  workflow_dispatch:


jobs:

  build_and_publish_84:
    name: Build and publish Docker image to Docker Hub
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "8.4"

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: eworkssk/php-fpm
          tags: 8.4, 8, latest
          registry: docker.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64/v8
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build_and_publish_83:
    name: Build and publish Docker image to Docker Hub
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "8.3"

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: eworkssk/php-fpm
          tags: 8.3
          registry: docker.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64/v8
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build_and_publish_82:
    name: Build and publish Docker image to Docker Hub
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "8.2"

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: eworkssk/php-fpm
          tags: 8.2
          registry: docker.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64/v8
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build_and_publish_81:
    name: Build and publish Docker image to Docker Hub
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "8.1"

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: eworkssk/php-fpm
          tags: 8.1
          registry: docker.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64/v8
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
  build_and_publish_74:
    name: Build and publish Docker image to Docker Hub
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "7.4"

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: eworkssk/php-fpm
          tags: 7.4
          registry: docker.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64/v8
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
